In [ ]:
import pandas as pd

In [ ]:
walmart=pd.read_csv("Walmart.csv")

In [ ]:
walmart.head()

Respondent  Product_Quality  E_Commerce  Technical_Support  \
0           1              8.5         3.9                2.5   
1           2              8.2         2.7                5.1   
2           3              9.2         3.4                5.6   
3           4              6.4         3.3                7.0   
4           5              9.0         3.4                5.2   

   Complaint_Resolution  Advertising  Product_Line  Salesforce_Image  \
0                   5.9          4.8           4.9               6.0   
1                   7.2          3.4           7.9               3.1   
2                   5.6          5.4           7.4               5.8   
3                   3.7          4.7           4.7               4.5   
4                   4.6          2.2           6.0               4.5   

   Competitive_Pricing  Warranty&Claims  Packaging  Order&Billing  \
0                  6.8              4.7        4.3            5.0   
1                  5.3              5.5        4.0            3.9   
2                  4.5              6.2        4.6            5.4   
3                  8.8              7.0        3.6            4.3   
4                  6.8              6.1        4.5            4.5   

   Price_Flexibility  Delivery_Speed  
0                5.1             3.7  
1                4.3             4.9  
2                4.0             4.5  
3                4.1             3.0  
4                3.5             3.5

In [ ]:
walmart.shape

(200, 14)

In [ ]:
x=walmart.iloc[:,1:]

In [ ]:
from sklearn.decomposition import PCA

In [ ]:
pcaModel=PCA(n_components=13)

In [ ]:
pcaModel.fit(x)

PCA(copy=True, iterated_power='auto', n_components=13, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [ ]:
pcaModel.explained_variance_

array([5.03307718, 4.17009745, 3.01231876, 2.08232407, 1.7598727 ,
       1.21633739, 0.73686911, 0.56591811, 0.27123224, 0.18682994,
       0.1684795 , 0.14154236, 0.00786803])

In [ ]:
pcaModel.explained_variance_ratio_

array([0.26007016, 0.2154781 , 0.15565313, 0.10759826, 0.09093649,
       0.06285083, 0.03807565, 0.02924223, 0.01401517, 0.00965391,
       0.00870571, 0.0073138 , 0.00040656])

In [ ]:
pcaModel.explained_variance_ratio_*100

array([26.00701604, 21.54781009, 15.56531314, 10.75982617,  9.09364906,
        6.28508266,  3.80756465,  2.92422327,  1.40151661,  0.96539136,
        0.87057061,  0.73138048,  0.04065587])

In [ ]:
import numpy as np

In [ ]:
np.cumsum(pcaModel.explained_variance_ratio_*100)

array([ 26.00701604,  47.55482614,  63.12013928,  73.87996544,
        82.9736145 ,  89.25869716,  93.06626181,  95.99048508,
        97.39200169,  98.35739305,  99.22796366,  99.95934413,
       100.        ])

In [ ]:
walmart.head(1)

Respondent  Product_Quality  E_Commerce  Technical_Support  \
0           1              8.5         3.9                2.5   

   Complaint_Resolution  Advertising  Product_Line  Salesforce_Image  \
0                   5.9          4.8           4.9               6.0   

   Competitive_Pricing  Warranty&Claims  Packaging  Order&Billing  \
0                  6.8              4.7        4.3            5.0   

   Price_Flexibility  Delivery_Speed  
0                5.1             3.7

In [ ]:
x=walmart[['Product_Quality','E_Commerce']]

In [ ]:
pcaModel=PCA()

In [ ]:
pcaModel.fit(x)

PCA(copy=True, iterated_power='auto', n_components=None, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [ ]:
pcaModel.components_

array([[-0.99961952,  0.02758297],
       [ 0.02758297,  0.99961952]])

In [ ]:
pcaModel.explained_variance_ratio_

array([0.76428358, 0.23571642])

In [ ]:
pcaModel=PCA(n_components=8)

In [ ]:
x=walmart.iloc[:,1:]

In [ ]:
pcaModel.fit(x)

PCA(copy=True, iterated_power='auto', n_components=8, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [ ]:
pd.DataFrame(pcaModel.components_)

0         1         2         3         4         5         6  \
0 -0.430251  0.006899 -0.312715 -0.233400 -0.012857 -0.492678  0.017316   
1  0.196277 -0.200681 -0.268891 -0.404501 -0.322217 -0.092655 -0.365899   
2  0.099156  0.044335 -0.776101  0.198956  0.137399  0.173937  0.063635   
3  0.076198  0.118380 -0.213915  0.119406  0.112076  0.192348  0.132366   
4  0.211077  0.329201  0.005544 -0.365592  0.503231 -0.080994  0.516619   
5 -0.605727 -0.004132  0.021772 -0.044879  0.172338 -0.164791  0.087911   
6  0.585560 -0.029479  0.050344 -0.007888  0.085386 -0.553143 -0.041339   
7 -0.007170 -0.386772  0.087039 -0.027190  0.734403  0.127772 -0.485203   

          7         8         9        10        11        12  
0  0.521613 -0.171361 -0.158096 -0.148671  0.227478 -0.138147  
1 -0.298209 -0.151451 -0.047960 -0.287778 -0.412694 -0.267749  
2 -0.100831 -0.339734  0.341353  0.146381  0.097343  0.141752  
3 -0.074622 -0.114659 -0.905005  0.039584 -0.106043  0.050216  
4 -0.003806  0.027400  0.142961 -0.213090 -0.290146 -0.189454  
5 -0.739646 -0.023072 -0.016549 -0.016125  0.132980 -0.013345  
6 -0.247509 -0.054845 -0.107283  0.113421  0.499968 -0.008766  
7  0.108120 -0.100807 -0.031539 -0.158686  0.024758  0.047997

In [ ]:
pd.DataFrame(pcaModel.transform(x))

0         1         2         3         4         5         6  \
0    1.261857  0.035032  2.612028  1.666938  0.306171  0.139477  1.365607   
1   -2.300377  0.892197  0.623032  1.530609 -2.834839  0.325148 -0.488818   
2   -3.109430 -0.222265  0.587819  1.384567  0.587419  0.970545  0.568521   
3    2.074414 -0.086868 -3.217971  0.226088  0.212849 -0.138574 -0.557674   
4   -0.565644  1.954175 -0.640682  0.432996 -0.759454 -1.043056  0.097709   
..        ...       ...       ...       ...       ...       ...       ...   
195 -0.716244  1.615277  4.007326 -0.106590  0.598246  1.964789 -0.405601   
196  1.765342 -3.558113  3.171253 -0.800679 -2.527507  0.287694 -0.195743   
197 -3.175512 -1.643683 -1.297863  0.508503  1.567962 -1.110793 -0.223519   
198 -0.102231 -5.255834 -0.309380  0.200532  1.219923  2.851427  0.171285   
199 -1.767066 -0.688252 -1.074384  4.534409  1.159135 -1.082030  0.065181   

            7  
0   -0.213154  
1    1.185301  
2    0.648647  
3    1.173456  
4   -0.911400  
..        ...  
195  0.183772  
196 -1.253719  
197  0.335275  
198 -0.526349  
199  0.257742  

[200 rows x 8 columns]